#!/bin/bash
# 运行容器，挂载上一级目录和宿主机的 .ssh 目录

# 自动判断是否需要 -it 参数（交互式终端才加）
DOCKER_TTY=""
if [ -t 0 ]; then
    DOCKER_TTY="-it"
fi

sudo docker run $DOCKER_TTY --rm \
        --privileged \
        --name $(date +%Y%m%d%H%M%S) \
        --shm-size 32G \
        --ulimit memlock=-1 \
        --tmpfs /tmp:exec,rw,size=32G \
	-u $(id -u) \
        -v "/opt:/opt" \
		-v $(cd .. && pwd):$(cd .. && pwd) \
		-v /etc/timezone:/etc/timezone \
		-v /etc/localtime:/etc/localtime:ro \
		-v ~/.ssh:/home/$(whoami)/.ssh \
		-v ~/.gitconfig:/home/$(whoami)/.gitconfig \
        --workdir $(cd .. && pwd) \
        --env WORKDIR=$(cd .. && pwd) \
        --env SCRIPTSNAME=$SCRIPTSNAME \
        --env SKIP_EXT=${SKIP_EXT:-} \
        --env SKIP_SYSTEM=${SKIP_SYSTEM:-} \
        --env NO_ADD_NEW=${NO_ADD_NEW:-} \
        --env DT_FW_DIR=${DT_FW_DIR:-} \
        --env EXT_VERBOSE=${EXT_VERBOSE:-} \
        ${IMAGENAME} \
        /bin/bash -c "$*"
