set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

get_filename_component(TOOLS_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(ROOT_DIR "${TOOLS_DIR}/.." ABSOLUTE)
set(SYSROOT "${ROOT_DIR}/prebuilds/sysroot")

# --- M2 Debian 应用工具链自动检测 (与 build.sh / environment-setup.sh 一致) ---
# M2 Debian = RK_DEBIAN_TRIXIE=y, rootfs.img 为 Debian trixie (glibc 2.41)。
# 默认使用 SDK 内置 rootfs 工具链 wrapper (Debian GCC 14/binutils 2.44)。
# 优先级: 用户 QPI_CROSS_COMPILE > SDK rootfs wrapper > 宿主 aarch64-linux-gnu- > SDK Linaro 10.3。
if(DEFINED ENV{QPI_CROSS_COMPILE} AND NOT "$ENV{QPI_CROSS_COMPILE}" STREQUAL "")
    set(CROSS_COMPILE "$ENV{QPI_CROSS_COMPILE}")
    set(TOOLCHAIN "")
elseif(EXISTS "${ROOT_DIR}/toolchains/m2-debian-rootfs-toolchain/bin/aarch64-linux-gnu-gcc")
    set(CROSS_COMPILE "aarch64-linux-gnu-")
    set(TOOLCHAIN "${ROOT_DIR}/toolchains/m2-debian-rootfs-toolchain")
elseif(EXISTS "/usr/bin/aarch64-linux-gnu-gcc")
    set(CROSS_COMPILE "aarch64-linux-gnu-")
    set(TOOLCHAIN "")
else()
    set(CROSS_COMPILE "aarch64-none-linux-gnu-")
    set(TOOLCHAIN "${ROOT_DIR}/toolchains/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu")
endif()

set(CMAKE_SYSROOT "${SYSROOT}")
if(NOT "${TOOLCHAIN}" STREQUAL "")
    set(CMAKE_C_COMPILER "${TOOLCHAIN}/bin/${CROSS_COMPILE}gcc")
    set(CMAKE_CXX_COMPILER "${TOOLCHAIN}/bin/${CROSS_COMPILE}g++")
    set(CMAKE_ASM_COMPILER "${TOOLCHAIN}/bin/${CROSS_COMPILE}gcc")
    set(CMAKE_AR "${TOOLCHAIN}/bin/${CROSS_COMPILE}ar")
    set(CMAKE_RANLIB "${TOOLCHAIN}/bin/${CROSS_COMPILE}ranlib")
    set(CMAKE_STRIP "${TOOLCHAIN}/bin/${CROSS_COMPILE}strip")
    set(CMAKE_NM "${TOOLCHAIN}/bin/${CROSS_COMPILE}nm")
    set(CMAKE_OBJCOPY "${TOOLCHAIN}/bin/${CROSS_COMPILE}objcopy")
    set(CMAKE_OBJDUMP "${TOOLCHAIN}/bin/${CROSS_COMPILE}objdump")
    set(CMAKE_READELF "${TOOLCHAIN}/bin/${CROSS_COMPILE}readelf")
else()
    set(CMAKE_C_COMPILER "${CROSS_COMPILE}gcc")
    set(CMAKE_CXX_COMPILER "${CROSS_COMPILE}g++")
    set(CMAKE_ASM_COMPILER "${CROSS_COMPILE}gcc")
    set(CMAKE_AR "${CROSS_COMPILE}ar")
    set(CMAKE_RANLIB "${CROSS_COMPILE}ranlib")
    set(CMAKE_STRIP "${CROSS_COMPILE}strip")
    set(CMAKE_NM "${CROSS_COMPILE}nm")
    set(CMAKE_OBJCOPY "${CROSS_COMPILE}objcopy")
    set(CMAKE_OBJDUMP "${CROSS_COMPILE}objdump")
    set(CMAKE_READELF "${CROSS_COMPILE}readelf")
endif()

set(CMAKE_FIND_ROOT_PATH "${SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/pkgconfig")
